force-app/main/default/objects/XAP_TRG_Trigger_Step__mdt/XAP_TRG_Trigger_Step__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Step</label>
    <pluralLabel>Trigger Steps</pluralLabel>
</CustomObject>

force-app/main/default/objects/XAP_TRG_Trigger_Step__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Trigger Framework/XAP_TRG_TriggerException.cls
public with sharing class XAP_TRG_TriggerException extends Exception {
    XAP_TRG_Trigger_Step__mdt step;
    XAP_TRG_TriggerStepFailure failure;

    public XAP_TRG_TriggerException(TypeException ex, XAP_TRG_Trigger_Step__mdt step){
        this('Failure during creation of ' + step.Class_Name__c, ex);
        this.step = step;
    }

    public XAP_TRG_TriggerException(XAP_TRG_TriggerStepFailure failure, XAP_TRG_Trigger_Step__mdt step){
        this('Failure during execution of ' + step.Class_Name__c, failure.getException());
        this.step = step;
        this.failure = failure;
    }
}