force-app/main/default/objects/XAP_TRG_Trigger_Settings__c/XAP_TRG_Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains settings to turn off triggers, collectively or individually, at the SObject level.</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/XAP_TRG_Trigger_Settings__c/fields/Account_Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Account_Trigger_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Account Trigger Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/XAP_TRG_Trigger_Settings__c/fields/All_Triggers_Enabled__c.field-meta.xml
<CustomField>
    <fullName>All_Triggers_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If true, triggers selected for each object will run. If false, no triggers will run</description>
    <label>All Triggers Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/XAP_TRG_Trigger_Settings__c/fields/Event_Recipes_Demo_Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Event_Recipes_Demo_Trigger_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Event Recipes Demo Trigger Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/tests/Test Data Factories/TEST_DummyXapTriggerSettingFactoryOutlet.cls
@IsTest
public class TEST_DummyXapTriggerSettingFactoryOutlet implements XFTY_DummySobjectFactoryOutletIntf {
	public static final String DEFAULT_NAME_PREFIX = 'Test XAP Trigger Settings Name';
	public static final Boolean DEFAULT_TRIGGER_ENABLED = true;
	public static final Boolean DEFAULT_ACCOUNT_TRIGGER_ENABLED = true;
	public static final Boolean DEFAULT_EVENT_RECIPES_DEMO_TRIGGER_ENABLED = true;

	private static final SObjectField PRIMARY_TARGET_FIELD = XAP_TRG_Trigger_Settings__c.Id;
	private static final XFTY_DummySObjectMasterTemplate MASTER_TEMPLATE = new XFTY_DummySObjectMasterTemplate(PRIMARY_TARGET_FIELD)
			.put(XAP_TRG_Trigger_Settings__c.Name, new XFTY_DummyDefaultValueIncrementingString(DEFAULT_NAME_PREFIX))
			.put(XAP_TRG_Trigger_Settings__c.Account_Trigger_Enabled__c, new XFTY_DummyDefaultValueExact(DEFAULT_ACCOUNT_TRIGGER_ENABLED))
			.put(XAP_TRG_Trigger_Settings__c.All_Triggers_Enabled__c, new XFTY_DummyDefaultValueExact(DEFAULT_TRIGGER_ENABLED))
			.put(XAP_TRG_Trigger_Settings__c.Event_Recipes_Demo_Trigger_Enabled__c, new XFTY_DummyDefaultValueExact(DEFAULT_EVENT_RECIPES_DEMO_TRIGGER_ENABLED));

	public SObjectField getPrimaryTargetField() {
		return PRIMARY_TARGET_FIELD;
	}

	public XFTY_DummySObjectMasterTemplate getMasterTemplate() {
		return MASTER_TEMPLATE;
	}

	public XFTY_DummySObjectBundle createBundle(
			List<SObject> templateSObjectList,
			XFTY_InsertModeEnum insertMode,
			XFTY_InsertInclusivityEnum inclusivity
	) {
		return XFTY_DummySObjectFactory.createBundle(MASTER_TEMPLATE, templateSObjectList, insertMode, inclusivity);
	}
	public static XAP_TRG_Trigger_Settings__c prepareIntegrationTest() {
		return (XAP_TRG_Trigger_Settings__c) new XFTY_DummySObjectSupplier(XAP_TRG_Trigger_Settings__c.SObjectType)
				.setInclusivity(XFTY_InsertInclusivityEnum.REQUIRED)
				.setInsertMode(XFTY_InsertModeEnum.NOW)
				.supply();
	}
}